image: Ubuntu1804
build: off
install:
- sh: yes | sudo apt-get install gcc-9-multilib g++-9-multilib
- sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 --slave /usr/bin/g++ g++ /usr/bin/g++-9
- sh: make
- sh: zip Florence.zip -r include

test_script:
- sh: make autotest
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))

artifacts:
- path: Florence.zip
  name: Florence headers
- path: out/Disk.bin
  name: Florence bootable disk
