image: Ubuntu1804
build: off
install:
- sh: make

test_script:
- sh: make autotest
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))

