usingnamespace @import("root").preamble;

/// Represents the physical location of a key on the keyboard, not affected by keyboard layouts
pub const Location = enum {
    escape,
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
    f13,
    f14,
    f15,
    f16,
    f17,
    f18,
    f19,
    f20,
    f21,
    f22,
    f23,
    f24,
    leftOf1,
    // Number key row, 123...0
    numberKey1,
    numberKey2,
    numberKey3,
    numberKey4,
    numberKey5,
    numberKey6,
    numberKey7,
    numberKey8,
    numberKey9,
    numberKey0,
    rightOf0,
    leftOfbackspace,
    backspace,
    // Top line,    QWERTY: QWERTY...
    tab,
    line1_1,
    line1_2,
    line1_3,
    line1_4,
    line1_5,
    line1_6,
    line1_7,
    line1_8,
    line1_9,
    line1_10,
    line1_11,
    line1_12,
    line1_13,
    // Middle line, QWERTY: ASDFGH...
    capsLock,
    line2_1,
    line2_2,
    line2_3,
    line2_4,
    line2_5,
    line2_6,
    line2_7,
    line2_8,
    line2_9,
    line2_10,
    line2_11,
    line2_12,
    enter,
    // Bottom line, QWERTY: ZXCVBN...
    leftShift,
    rightOfleftShift,
    line3_1,
    line3_2,
    line3_3,
    line3_4,
    line3_5,
    line3_6,
    line3_7,
    line3_8,
    line3_9,
    line3_10,
    rightShift,

    // Control keys along the bottom
    leftCtrl,
    rightCtrl,
    leftSuper,
    rightSuper,
    leftAlt,
    rightAlt,
    spacebar,
    optionKey, // Between right super and right control

    // Directional keys
    arrowUp,
    arrowleft,
    arrowDown,
    arrowright,

    // Group above directional keys
    printScreen,
    pauseBreak,
    scrollLock,
    insert,
    home,
    pageUp,
    delete,
    end,
    pageDown,

    // numpad
    numLock,
    numpadDivision,
    numpadMultiplication,
    numpad7,
    numpad8,
    numpad9,
    numpadSubtraction,
    numpad4,
    numpad5,
    numpad6,
    numpadAddition,
    numpad1,
    numpad2,
    numpad3,
    numpad0,
    numpadPoint,
    numpadEnter,

    // Multimedia keys
    mediaStop,
    mediaRewind,
    mediaPausePlay,
    mediaForward,
    mediaMute,
    mediaVolumeUp,
    mediaVolumeDown,
};

/// Represent the intent of pressing the key, affected by keyboard layout
pub const Input = enum {
    // Traditional numbers
    @"1",
    @"2",
    @"3",
    @"4",
    @"5",
    @"6",
    @"7",
    @"8",
    @"9",
    @"0",

    // Traditional letters
    q,
    w,
    e,
    r,
    t,
    y,
    u,
    i,
    o,
    p,
    a,
    s,
    d,
    f,
    g,
    h,
    j,
    k,
    l,
    z,
    x,
    c,
    v,
    b,
    n,
    m,

    // Control keys
    spacebar,
    optionKey,
    backspace,
    tab,
    escape,
    capsLock,
    enter,

    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
    f13,
    f14,
    f15,
    f16,
    f17,
    f18,
    f19,
    f20,
    f21,
    f22,
    f23,
    f24,

    // Modifier keys
    leftShift,
    rightShift,
    leftCtrl,
    rightCtrl,
    leftSuper,
    rightSuper,
    leftAlt,
    rightAlt,

    // The buttons traditionally above the arrow keys
    printScreen,
    pauseBreak,
    scrollLock,
    insert,
    home,
    pageUp,
    delete,
    end,
    pageDown,

    // arrow keys
    arrowUp,
    arrowleft,
    arrowDown,
    arrowright,

    // Punctuation
    exclamationMark,
    quotationMark,
    hash,
    currencySign,
    percent,
    ampersand,
    forwardSlash,
    backSlash,
    questionMark,
    at,
    dollarSign,
    caret,
    asterisk,
    period,
    comma,
    colon,
    semicolon,
    plus,
    minus,
    underscore,
    equals,
    verticalBar,
    tilde,
    backTick,
    apostrophe,
    poundSign,
    plusminus,
    acute,
    umlaut,
    euroSign,
    yenCurrency,
    paragraphSign,
    sectionSign,

    openSqBracket,
    closeSqBracket,
    openCurlyBrace,
    closeCurlyBrace,
    openParen,
    closeParen,
    lessThan,
    greaterThan,

    // numpad
    numLock,
    numpadDivision,
    numpadMultiplication,
    numpad7,
    numpad8,
    numpad9,
    numpadSubtraction,
    numpad4,
    numpad5,
    numpad6,
    numpadAddition,
    numpad1,
    numpad2,
    numpad3,
    numpad0,
    numpadPoint,
    numpadEnter,

    // Multimedia keys
    mediaStop,
    mediaRewind,
    mediaPausePlay,
    mediaForward,
    mediaMute,
    mediaVolumeUp,
    mediaVolumeDown,

    // International letters
    aWithUmlaut,
    oWithUmlaut,
    aWithRing,
    slashedO,
    ash,
};

pub const wasd_directional = .{
    .up = KeyLocation.line1_2,
    .left = KeyLocation.line2_1,
    .down = KeyLocation.line2_2,
    .right = KeyLocation.line2_3,
};

pub const arrow_directional = .{
    .up = KeyLocation.arrowUp,
    .left = KeyLocation.arrowleft,
    .down = KeyLocation.arrowDown,
    .right = KeyLocation.arrowright,
};

pub const numpad_directional = .{
    .up = KeyLocation.numpad8,
    .left = KeyLocation.numpad4,
    .down = KeyLocation.numpad2,
    .right = KeyLocation.numpad6,
};
