/// Represents the physical location of a key on the keyboard, not affected by keyboard layouts
pub const Location = enum {
    escape,
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
    f13,
    f14,
    f15,
    f16,
    f17,
    f18,
    f19,
    f20,
    f21,
    f22,
    f23,
    f24,
    left_of1,
    // Number key row, 123...0
    number_key1,
    number_key2,
    number_key3,
    number_key4,
    number_key5,
    number_key6,
    number_key7,
    number_key8,
    number_key9,
    number_key0,
    right_of0,
    left_of_backspace,
    backspace,
    // Top line,    QWERTY: QWERTY...
    tab,
    line1_1,
    line1_2,
    line1_3,
    line1_4,
    line1_5,
    line1_6,
    line1_7,
    line1_8,
    line1_9,
    line1_10,
    line1_11,
    line1_12,
    line1_13,
    // Middle line, QWERTY: ASDFGH...
    capslock,
    line2_1,
    line2_2,
    line2_3,
    line2_4,
    line2_5,
    line2_6,
    line2_7,
    line2_8,
    line2_9,
    line2_10,
    line2_11,
    line2_12,
    enter,
    // Bottom line, QWERTY: ZXCVBN...
    left_shift,
    right_of_left_shift,
    line3_1,
    line3_2,
    line3_3,
    line3_4,
    line3_5,
    line3_6,
    line3_7,
    line3_8,
    line3_9,
    line3_10,
    right_shift,

    // Control keys along the bottom
    left_ctrl,
    right_ctrl,
    left_super,
    right_super,
    left_alt,
    right_alt,
    spacebar,
    option_key, // Between right super and right control

    // Directional keys
    arrow_up,
    arrow_left,
    arrow_down,
    arrow_right,

    // Group above directional keys
    print_screen,
    pause_break,
    scroll_lock,
    insert,
    home,
    page_up,
    delete,
    end,
    page_down,

    // numpad
    numlock,
    numpad_div,
    numpad_mul,
    numpad7,
    numpad8,
    numpad9,
    numpad_sub,
    numpad4,
    numpad5,
    numpad6,
    numpad_add,
    numpad1,
    numpad2,
    numpad3,
    numpad0,
    numpad_point,
    numpad_enter,

    // Multimedia keys
    media_stop,
    media_rewind,
    media_pause_play,
    media_forward,
    media_mute,
    media_volume_up,
    media_volume_down,
};

/// Represent the intent of pressing the key, affected by keyboard layout
pub const Input = enum {
    // Traditional numbers
    @"1",
    @"2",
    @"3",
    @"4",
    @"5",
    @"6",
    @"7",
    @"8",
    @"9",
    @"0",

    // Traditional letters
    q,
    w,
    e,
    r,
    t,
    y,
    u,
    i,
    o,
    p,
    a,
    s,
    d,
    f,
    g,
    h,
    j,
    k,
    l,
    z,
    x,
    c,
    v,
    b,
    n,
    m,

    // Control keys
    spacebar,
    option_key,
    backspace,
    tab,
    escape,
    capslock,
    enter,

    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
    f13,
    f14,
    f15,
    f16,
    f17,
    f18,
    f19,
    f20,
    f21,
    f22,
    f23,
    f24,

    // Modifier keys
    left_shift,
    right_shift,
    left_ctrl,
    right_ctrl,
    left_super,
    right_super,
    left_alt,
    right_alt,

    // The buttons traditionally above the arrow keys
    print_screen,
    pause_break,
    scroll_lock,
    insert,
    home,
    page_up,
    delete,
    end,
    page_down,

    // arrow keys
    arrow_up,
    arrow_left,
    arrow_down,
    arrow_right,

    // Punctuation
    exclamation_mark,
    quotation_mark,
    hash,
    currency_sign,
    percent,
    ampersand,
    forward_slash,
    back_slash,
    question_mark,
    at,
    dollar_sign,
    caret,
    asterisk,
    period,
    comma,
    colon,
    semicolon,
    plus,
    minus,
    underscore,
    equals,
    vertical_bar,
    tilde,
    back_tick,
    apostrophe,
    pound_sign,
    plusminus,
    acute,
    umlaut,
    euro_sign,
    yen_sign,
    paragraph_sign,
    section_sign,

    open_sq_bracket,
    close_sq_bracket,
    open_curly_brace,
    close_curly_brace,
    open_paren,
    close_paren,
    less_than,
    greater_than,

    // numpad
    numlock,
    numpad_div,
    numpad_mul,
    numpad7,
    numpad8,
    numpad9,
    numpad_sub,
    numpad4,
    numpad5,
    numpad6,
    numpad_add,
    numpad1,
    numpad2,
    numpad3,
    numpad0,
    numpad_point,
    numpad_enter,

    // Multimedia keys
    media_stop,
    media_rewind,
    media_pause_play,
    media_forward,
    media_mute,
    media_volume_up,
    media_volume_down,

    // International letters
    a_with_umlaut,
    o_with_umlaut,
    a_with_ring,
    slashedO,
    ash,
};

pub const wasd_directional = .{
    .up = Location.line1_2,
    .left = Location.line2_1,
    .down = Location.line2_2,
    .right = Location.line2_3,
};

pub const arrow_directional = .{
    .up = Location.arrow_up,
    .left = Location.arrow_left,
    .down = Location.arrow_down,
    .right = Location.arrow_right,
};

pub const numpad_directional = .{
    .up = Location.numpad8,
    .left = Location.numpad4,
    .down = Location.numpad2,
    .right = Location.numpad6,
};
